version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  # api:
  #   container_name: freemerchandise-api
  #   build:
  #     context: ./
  #     target: production
  #   image: freemerchandise-api
  #   depends_on:
  #     - db
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASS}
  #     DB_NAME: ${DB_NAME}
  #   links:
  #     - db
  #   volumes:
  #     - ./:/src
volumes:
  db:
    driver: local